spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # mysql docker container address
    url: jdbc:mysql://db:3306/authdb
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.springframework: DEBUG
